media: src/assets
content:
    - name: news
      label: News
      path: src/content/news
      type: collection
      view:
          fields: [title, pubDate, image, link]
      fields:
          - { name: title, label: Title, type: string }
          - { name: pubDate, label: Date Added, type: date }
          - { name: image, label: Image, type: image }
          - { name: link, label: Link, type: string }
          - { name: body, label: Body, type: rich-text }
          - name: map
            label: Map PDF
            type: image
              categories: document
